version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    env_file:
      - .env
    depends_on:
      - hana
    networks:
      - app-network

  frontend-react:
    build:
      context: .
      dockerfile: frontend/react-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  frontend-streamlit:
    build:
      context: .
      dockerfile: frontend/streamlit-app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network

  hana:
    image: store/saplabs/hanaexpress:2.00.057.00
    ports:
      - "39013:39013"
      - "39015:39015"
      - "39017:39017"
      - "39030:39030"
      - "39041:39041"
      - "39042:39042"
      - "39043:39043"
      - "39044:39044"
      - "39045:39045"
      - "8090:8090"
    environment:
      - MASTER_PASSWORD=YourStrongPassword123
      - SYSTEM_PASSWORD=YourStrongPassword123
    volumes:
      - hana-data:/hana/mounts
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  hana-data:
  grafana-data:

networks:
  app-network:
    driver: bridge 